import React from "react";
import ToAnotherLevel from "../../../images/TakeToAnotherLevel.svg";
import Percentage from "../../../images/Percentage.svg";
import "./landingPage.scss";
import WriteIcon from "../../../images/icons/write.svg";
import ManageIcon from "../../../images/icons/manage.svg";
import AnalyticsIcon from "../../../images/icons/analytics.svg";
import CardsTodo from "./card";

const LandingPage = () => (
  <div>
    <div className="landingPage1stRow">
      {/* first row */}
      <div className="imageWrapper container">
        <img src={ToAnotherLevel} alt="Take Todo To Another level" />
        <img
          src={Percentage}
          alt="Todo Percentage"
          className="percentageImage"
        />
      </div>
    </div>

    {/* second row and third Row */}
    <div className="container thirdRow">
      <div className="cardsWrapper">
        <CardsTodo
          image={WriteIcon}
          imageAlt="Write Todo"
          title="Create a Todo List"
          description="Write Your daily/weekly/monthly todo items on your own controlled
              environment"
        />
        <CardsTodo
          image={ManageIcon}
          imageAlt="Manage Todo List"
          title="Manage"
          description="Manage your todo items over time. Mark as complete/incomplete, add
                comments, set reminders, etc"
        />
        <CardsTodo
          image={AnalyticsIcon}
          imageAlt="Analytics"
          title="Analytics"
          description="Get in-depth analytics for all your todo items. Track your progress,
                get suggestions on your data."
        />
      </div>

      <div className="thirdSecondRow">
        <center>
          <h2 className="cardTitle whyUseLPTitle">Why Use LP</h2>
        </center>

        <div className="whyUseLPWrapper">
          <div className="videoPlayer">
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            LP Video Tutorial
          </div>

          <div className="whyUseLPDescription">
            <ul>
              <li>Complete control of your environment</li>
              <li>Automated reminders</li>
              <li>Real-time based analytics</li>
              <li>Share your success/outputs</li>
              <li>Manage your history</li>
              <li>Weekly autogenerated summary</li>
              <li>Collaborate with your team(teams todo)</li>
            </ul>
          </div>
        </div>
      </div>
      <br />
      <br />
    </div>
  </div>
);

export default LandingPage;
